import = ["/home/lhaug/.config/alacritty/themes/dracula.toml"]

[font]
size = 13.0

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[shell]
program = "/bin/fish"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 4
y = 4
